add 414. Third Maximum Number
ryuji0123/review_leetcode pull request #100
Opened 2021-05-23 09:52 UTC by tkkawa

Please check my code.

2021-05-29 09:01 UTC, ryuji0123 requested changes
use set

2021-05-29 09:01 UTC, ryuji0123 commented on 414_third-maximum-number.py
> +        sort_nums = sorted(nums)
sorted_nums

2021-06-01 02:06 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-06 10:48 UTC, ryuji0123 approved these changes

2021-06-08 01:39 UTC, merged