add 1379. Find a Corresponding Node of a Binary Tree in a Clone of Th…
ryuji0123/review_leetcode pull request #112
Opened 2021-05-26 14:27 UTC by tkkawa

Please check my code.

2021-05-29 08:32 UTC, ryuji0123 requested changes

2021-05-29 08:32 UTC, ryuji0123 commented on 1379_find-a-corresponding-node-of-a-binary-tree-in-a-clone-of-that-tree.py
> +            if not curr_node:
if curr_node is None:

2021-06-01 02:12 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-06 10:48 UTC, ryuji0123 approved these changes

2021-06-08 01:41 UTC, merged