add 671. Second Minimum Node In a Binary Tree
ryuji0123/review_leetcode pull request #12
Opened 2021-05-11 14:35 UTC by tkkawa

Please check my code.

2021-05-12 09:58 UTC, ryuji0123 approved these changes

2021-05-12 09:58 UTC, ryuji0123 requested changes

2021-05-12 09:58 UTC, ryuji0123 commented on 671_second-minimum-node-in-a-binary-tree.py
> +            node = stack.popleft()
cur_node

2021-05-16 02:58 UTC, tkkawa commented
I modified the code.

2021-06-06 11:02 UTC, ryuji0123 approved these changes

2021-06-08 01:25 UTC, merged