add 1784. Check if Binary String Has at Most One Segment of Ones
ryuji0123/review_leetcode pull request #16
Opened 2021-05-11 14:43 UTC by tkkawa

Please check my code.

2021-05-17 13:46 UTC, ryuji0123 requested changes

2021-05-17 13:46 UTC, ryuji0123 commented on 1784_check-if-binary-string-has-at-most-one-segment-of-ones.py
> +            if s[i] == '1' and s[i] == s[i-1]:
if s[i] == s[i-1] == '1':

2021-06-08 01:30 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-13 04:55 UTC, ryuji0123 approved these changes

2021-06-13 12:05 UTC, merged