add 101. Symmetric Tree
ryuji0123/review_leetcode pull request #28
Opened 2021-05-12 08:49 UTC by kobakobashu

time : 50m
Please check my code.

2021-05-12 09:55 UTC, ryuji0123 requested changes

2021-05-12 09:55 UTC, ryuji0123 commented on 101_symmetric-tree.py
> +    def check_mirror(self, left, right):
also add type annotation here

2021-05-14 10:03 UTC, kobakobashu commented
I added type annotation in the check_mirror function.  Please check my code.

2021-06-06 11:03 UTC, ryuji0123 approved these changes

2021-06-07 04:21 UTC, merged