add 110. Balanced Binary Tree
ryuji0123/review_leetcode pull request #32
Opened 2021-05-12 09:11 UTC by kobakobashu

time : 35m
Please check my code.

2021-05-12 09:56 UTC, ryuji0123 approved these changes

2021-05-12 09:56 UTC, ryuji0123 requested changes

2021-05-12 09:56 UTC, ryuji0123 commented on 110_balanced-binary-tree.py
> +    def depth(self, node):
add type annotation and docstring

2021-05-14 10:34 UTC, kobakobashu commented
I added type annotation and docstring.  Please check my code.

2021-06-06 11:04 UTC, ryuji0123 approved these changes

2021-06-07 04:22 UTC, merged