add 122. Best Time to Buy and Sell Stock II
ryuji0123/review_leetcode pull request #38
Opened 2021-05-12 09:39 UTC by kobakobashu

time : 10m
Please check my code.

2021-05-12 09:43 UTC, ryuji0123 requested changes

2021-05-12 09:43 UTC, ryuji0123 commented on 122_best-time-to-buy-and-sell-stock-ii.py
> +                sum_profit_to_day += (cur_price - pre_price)
sum_profit_to_day += cur_price - pre_price

2021-05-14 10:16 UTC, kobakobashu commented
I removed "()".  Please check my code.

2021-06-06 11:04 UTC, ryuji0123 approved these changes

2021-06-07 04:22 UTC, merged