add 160. Intersection of Two Linked Lists
ryuji0123/review_leetcode pull request #46
Opened 2021-05-12 10:03 UTC by kobakobashu

time : 30m
Please check my code.

2021-05-12 10:11 UTC, ryuji0123 requested changes
insert lines appropriately to make your code's structure clear

2021-05-12 10:11 UTC, ryuji0123 commented on 160_intersection-of-two-linked-lists.py
> +        if len_headB < len_headA:
elif

2021-05-14 10:24 UTC, kobakobashu commented
I inserted lines appropriately and changed "if" to "elif".  Please check my code.

2021-06-06 11:04 UTC, ryuji0123 approved these changes

2021-06-07 04:23 UTC, merged