add 219. Contains Duplicate II
ryuji0123/review_leetcode pull request #86
Opened 2021-05-20 08:36 UTC by kobakobashu

time : 20m
Please check my code.

2021-05-29 08:54 UTC, ryuji0123 requested changes

2021-05-29 08:54 UTC, ryuji0123 commented on 219_contains-duplicate-ii.py
> +        ref = {}
ref is unclear

2021-06-01 11:29 UTC, kobakobashu commented
I renamed unclear name "ref".  Please check my code.

2021-06-15 07:45 UTC, tkkawa approved these changes
LGTM

2021-06-15 12:40 UTC, ryuji0123 approved these changes

2021-06-22 08:59 UTC, merged