add 228. Summary Ranges
ryuji0123/review_leetcode pull request #90
Opened 2021-05-21 10:22 UTC by kobakobashu

time : 25m

2021-05-21 10:23 UTC, kobakobashu commented
Please check my code.

2021-05-29 09:07 UTC, ryuji0123 requested changes

2021-05-29 09:07 UTC, ryuji0123 commented on 228_summary-ranges.py
> +            pre_num = nums[i]
insert one line

2021-06-01 11:32 UTC, kobakobashu commented
I inserted one line.  Please check my code.

2021-06-15 07:58 UTC, tkkawa approved these changes
LGTM

2021-06-15 12:41 UTC, ryuji0123 approved these changes

2021-06-22 09:00 UTC, merged