add 941. Valid Mountain Array
ryuji0123/review_leetcode pull request #93
Opened 2021-05-21 12:37 UTC by tkkawa

Please check my code.

2021-05-29 09:05 UTC, ryuji0123 requested changes
Write like this with splitting lines

```py
N = len(arr)
        max_idx = arr.index(max(arr))
        return 0 < max_idx < N - 1 and all(arr[i] < arr[i + 1] for i in range(max_idx)) and all(arr[i + 1] < arr[i] for i in range(max_idx, N - 1))
```

2021-05-29 09:05 UTC, ryuji0123 commented on 941_valid-mountain-array.py
> +        increase = decrease = False
is_increasing

2021-06-01 01:47 UTC, tkkawa commented
I modified the code.
Please check my code.

2021-06-06 10:49 UTC, ryuji0123 approved these changes

2021-06-08 01:36 UTC, merged